### ISSUE TITLE
KeyError: 'results'

### ISSUE THREAD

**Issue by gaspan** [pthrasher/sentiment#1]
File "D:\sentiment app\sentiment-master\twitter_sentiment.py", line 44, in get_tweets
    tweets += [result['text'] for result in content['results']]

**Comment by pthrasher** [comment]
The twitter API has changed since I wrote this. I don't have any interest in keeping this up as it was just a project for me to learn. However, If you fix it and want to submit a pull request, I'd be happy to take one. :-)
